version: "3.8"

services:
  web:
    image: ghcr.io/${GITHUB_REPOSITORY}/web:latest
    container_name: npchweb_starter_next
    build: !reset null
    volumes: !reset []
    command: !reset null
    environment:
      - NODE_ENV=production
